rabbitmq:
  image: rabbitmq:3.6.1-management
  hostname: rabbitmq
  ports:
      - "15672:15672"

sample-hystrix-app1:
  image: sample-hystrix-app:1.0.1-SNAPSHOT
  hostname: samplehystrixapp1
  links:
    - rabbitmq
  environment:
     SPRING_PROFILES_ACTIVE: docker
     RABBITMQ_HOST: rabbitmq
  ports:
    - "7080:8080"

sample-hystrix-app2:
  image: sample-hystrix-app:1.0.1-SNAPSHOT
  hostname: samplehystrixapp2
  links:
    - rabbitmq
  environment:
     SPRING_PROFILES_ACTIVE: docker
     RABBITMQ_HOST: rabbitmq
  ports:
    - "7081:8080"

sample-hystrix-app3:
  image: sample-hystrix-app:1.0.1-SNAPSHOT
  hostname: samplehystrixapp3
  links:
    - rabbitmq
  environment:
     SPRING_PROFILES_ACTIVE: docker
     RABBITMQ_HOST: rabbitmq
  ports:
    - "7082:8080"

sample-turbine-amqp:
  image: sample-turbine-amqp:1.0.1-SNAPSHOT
  hostname: sampleturbineamqp
  links:
    - rabbitmq
  environment:
     SPRING_PROFILES_ACTIVE: docker
     RABBITMQ_HOST: rabbitmq
  ports:
    - "8085:8080"

sample-hystrix-dashboard:
  image: sample-hystrix-dashboard:1.0.1-SNAPSHOT
  hostname: samplehystrixdashboard
  links:
    - sample-turbine-amqp
  environment:
     SPRING_PROFILES_ACTIVE: docker
  ports:
    - "9080:8080"
